# Python related
alias virton="source pyenv/bin/activate"
alias genv3="source $HOME/.general_py3/bin/activate"
alias genv2="source $HOME/.general_py2/bin/activate"

# add utils to PATH
export PATH=$PATH:$HOME/workspace/utils/bin

# hides user@machine:/current/path/
# promt becomes just ">", much nicer
export PS1='> '

